### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by amccloud** [realkosty/sentry-micro-frontend#2]
Hello, I'd love to contribute to this research but the licensing is unclear. In the package.json and header of each method, there appears to be a modified [ISC license](https://opensource.org/licenses/ISC). Can you add a LICENSE file to this repo with clear copyright?

> All the code included in this repository is intended as example only and should NOT be adopted for use in production software without first undergoing full review and rigorous testing. This code is provided on an "AS-IS" basis without warranty of any kind, either express or implied, including without limitation any implied warranties of condition,  uninterrupted use, merchantability, fitness for a particular purpose, or non-infringement. The details of your application or component, architecture of the host-application, and  your target browser support, among many other things, may require you to modify this code. Issues regarding these code examples should be submitted through GitHub.

I would PR this but I'm not clear if you or Sentry owns copyright.

**Comment by realkosty** [comment]
Hi Andrew. Thank you for offering to contribute! 
Let me first check with our legal real quick as to which license and copyright should be used 😄

**Comment by realkosty** [comment]
Done!

**Comment by realkosty** [comment]
Also please note this repo will be migrated to `sentry-demos` account
